// Languages the word-game tools know about. `available: true` means a
// dictionary exists at /data/<code>/ (generated by scripts/build-word-index.mjs).
// Others are listed so the picker is visibly ready for them, without
// pretending they work yet.
export const LANGUAGES = [
  { code: 'en', label: 'English', available: true },
  { code: 'fr', label: 'French', available: false },
  { code: 'es', label: 'Spanish', available: false },
  { code: 'de', label: 'German', available: false },
];

export const DEFAULT_LANGUAGE = 'en';
